name: nikhils_program_rotamer
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python>=3.9
  - numpy>=1.20,<2
  - scipy
  - cvxpy<1.6
  - pyscipopt
  - scip==9.1
  - pandas>=1.2
  - pyparsing>=2.2.0
  - cvxopt
  - tqdm
  - cctbx-base
  - rdkit
  - matplotlib
  - biotite
  - coot-headless
